---
- name: grub update
  ansible.builtin.shell: update-grub
  notify: change_requires_reboot
  failed_when: false

- name: reload gdm3
  ansible.builtin.shell: dpkg-reconfigure gdm3
  failed_when: false

- name: restart postfix
  ansible.builtin.service:
      name: postfix
      state: restarted

- name: restart exim4
  ansible.builtin.service:
      name: exim4
      state: restarted

- name: sysctl flush ipv4 route table
  ansible.posix.sysctl:
      name: net.ipv4.route.flush
      value: '1'
      sysctl_set: true
  when: ansible_virtualization_type != "docker"

- name: reload ufw
  community.general.ufw:
      state: reloaded

- name: sysctl flush ipv6 route table
  ansible.posix.sysctl:
      name: net.ipv6.route.flush
      value: '1'
      sysctl_set: true
  when: ansible_virtualization_type != "docker"

- name: restart auditd
  ansible.builtin.service:
      name: auditd
      state: restarted
  when:
      - not ubtu20cis_skip_for_travis
  tags:
      - skip_ansible_lint

- name: restart rsyslog
  ansible.builtin.service:
      name: rsyslog
      state: restarted

- name: restart sshd
  ansible.builtin.service:
      name: sshd
      state: restarted

- name: reload gdm
  ansible.builtin.shell: dpkg-reconfigure gdm3

- name: change_requires_reboot
  set_fact:
      change_requires_reboot: true
