---
# ---------------
# ---------------
# NFTables is unsupported with this role. However I have the actions commented out as a guide
# ---------------
# ---------------
- name: "3.5.2.1 | AUDIT | Ensure nftables is installed"
  block:
      - name: "3.5.2.1 | AUDIT | Ensure nftables is installed"
        ansible.builtin.debug:
            msg: "Warning!! NFTables is not supported in this role. Please use UFW, iptables, or manually manage nftables"

      - name: "3.5.2.1 | AUDIT | Ensure nftables is installed | Warn Count"
        ansible.builtin.import_tasks: warning_facts.yml
  vars:
      warn_control_id: '3.5.2.x NFTables not supported'
  when:
      - ubtu20cis_rule_3_5_2_1
      - ubtu20cis_firewall_package == "nftables"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - audit
      - rule_3.5.2.1
      - nftables

- name: "3.5.2.2 | AUDIT | Ensure ufw is uninstalled or disabled with nftables"
  ansible.builtin.debug:
      msg: "Warning!! NFTables is not supported in this role. Please use UFW, iptables, or manually manage nftables"
  # ansible.builtin.package:
  #     name: ufw
  #     state: absent
  when:
      - ubtu20cis_rule_3_5_2_2
      - ubtu20cis_firewall_package == "nftables"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - audit
      - rule_3.5.2.2
      - nftables

- name: "3.5.2.3 | AUDIT | Ensure iptables are flushed with nftables"
  ansible.builtin.debug:
      msg: "Warning!! NFTables is not supported in this role. Please use UFW, iptables, or manually manage nftables"
  # iptables:
  #     flush: yes
  when:
      - ubtu20cis_rule_3_5_2_3
      - ubtu20cis_firewall_package == "nftables"
  tags:
      - level1-server
      - level1-workstation
      - manual
      - audit
      - rule_3.5.2.3
      - nftables

- name: "3.5.2.4 | AUDIT | Ensure a nftables table exists"
  ansible.builtin.debug:
      msg: "Warning!! NFTables is not supported in this role. Please use UFW, iptables, or manually manage nftables"
  # command: "nft create table {{ ubtu20cis_nftables_table_name }}"
  # changed_when: ubtu20cis_3_5_2_4_new_table.rc == 0
  # failed_when: false
  # check_mode: false
  # register: ubtu20cis_3_5_2_4_new_table
  when:
      - ubtu20cis_rule_3_5_2_4
      - ubtu20cis_firewall_package == "nftables"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_3.5.2.4
      - nftables

- name: "3.5.2.5 | AUDIT | Ensure nftables base chains exist"
  ansible.builtin.debug:
      msg: "Warning!! NFTables is not supported in this role. Please use UFW, iptables, or manually manage nftables"
  # block:
  #     - name: "3.5.2.5 | PATCH | Ensure nftables base chains exist | Input entry"
  #       shell: 'nft create chain {{ ubtu20cis_nftables_table_name }} input { type filter hook input priority 0 \; }'
  #       changed_when: ubtu20cis_3_5_2_5_base_chains_input.rc == 0
  #       failed_when: false
  #       register: ubtu20cis_3_5_2_5_base_chains_input

  #     - name: "3.5.2.5 | PATCH | Ensure nftables base chains exist | Forward entry"
  #       shell: 'nft create chain {{ ubtu20cis_nftables_table_name }} forward { type filter hook forward priority 0 \; }'
  #       changed_when: ubtu20cis_3_5_2_5_base_chains_forward.rc == 0
  #       failed_when: false
  #       register: ubtu20cis_3_5_2_5_base_chains_forward

  #     - name: "3.5.2.5 | PATCH | Ensure nftables base chains exist | Output entry"
  #       shell: 'nft create chain {{ ubtu20cis_nftables_table_name }} output { type filter hook output priority 0 \; }'
  #       changed_when: ubtu20cis_3_5_2_5_base_chains_output.rc == 0
  #       failed_when: false
  #       register: ubtu20cis_3_5_2_5_base_chains_output
  when:
      - ubtu20cis_rule_3_5_2_5
      - ubtu20cis_firewall_package == "nftables"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - audit
      - rule_3.5.2.5
      - nftables

- name: "3.5.2.6 | AUDIT | Ensure nftables loopback traffic is configured"
  ansible.builtin.debug:
      msg: "Warning!! NFTables is not supported in this role. Please use UFW, iptables, or manually manage nftables"
  # block:
  #     - name: "3.5.2.6 | AUDIT | Ensure nftables loopback traffic is configured | Get input iif lo accept status"
  #       shell: nft list ruleset | awk '/hook input/,/}/' | grep 'iif "lo" accept'
  #       changed_when: false
  #       failed_when: false
  #       check_mode: false
  #       register: ubtu20cis_3_5_2_6_loopback_iif_status

  #     - name: "3.5.2.6 | AUDIT | Ensure nftables loopback traffic is configured | Get input iif lo accept status"
  #       shell: nft list ruleset | awk '/hook input/,/}/' | grep 'ip saddr'
  #       changed_when: false
  #       failed_when: false
  #       check_mode: false
  #       register: ubtu20cis_3_5_2_6_loopback_input_drop_status

  #     - name: "3.5.2.6 | AUDIT | Ensure nftables loopback traffic is configured | Get input iif lo accept status"
  #       shell: nft list ruleset | awk '/hook input/,/}/' | grep 'ip6 saddr'
  #       changed_when: false
  #       failed_when: false
  #       check_mode: false
  #       register: ubtu20cis_3_5_2_6_loopback_ipv6_drop_status

  #     - name: "3.5.2.6 | PATCH | Ensure nftables loopback traffic is configured | Loopback iif lo accept"
  #       command: 'nft add rule inet {{ ubtu20cis_nftables_table_name }} input iif lo accept'
  #       changed_when: ubtu20cis_3_5_2_6_loopback_iif.rc == 0
  #       failed_when: false
  #       register: ubtu20cis_3_5_2_6_loopback_iif
  #       when: "'iif \"lo\" accept' not in ubtu20cis_3_5_2_6_loopback_iif_status.stdout"

  #     - name: "3.5.2.6 | PATCH | Ensure nftables loopback traffic is configured | Loopback input drop"
  #       command: 'nft add rule inet {{ ubtu20cis_nftables_table_name }} input ip saddr 127\.0\.0\.0\/8 counter drop'
  #       changed_when: ubtu20cis_3_5_2_6_loopback_input_drop.rc == 0
  #       failed_when: false
  #       register: ubtu20cis_3_5_2_6_loopback_input_drop
  #       when:
  #        - "'ip saddr 127.0.0.0/8' not in ubtu18cis_3_5_3_4_loopback_input_drop_status.stdout"
  #        - "'drop' not in ubtu20cis_3_5_2_6_loopback_input_drop_status.stdout"

  #     - name: "3.5.2.6 | PATCH | Ensure nftables loopback traffic is configured | Loopback ipv6 drop"
  #       command: 'nft add rule inet {{ ubtu20cis_nftables_table_name }} input ip6 saddr ::1 counter drop'
  #       changed_when: ubtu20cis_3_5_2_6_loopback_ipv6_drop.rc == 0
  #       failed_when: false
  #       register: ubtu20cis_3_5_2_6_loopback_ipv6_drop
  #       when:
  #           - "'ip6 saddr' not in ubtu20cis_3_5_2_6_loopback_ipv6_drop_status.stdout"
  #           - "'drop' not in ubtu20cis_3_5_2_6_loopback_ipv6_drop_status.stdout"
  when:
      - ubtu20cis_rule_3_5_2_6
      - ubtu20cis_firewall_package == "nftables"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - audit
      - rule_3.5.2.6
      - nftables

- name: "3.5.2.7 | AUDIT | Ensure nftables outbound and established connections are configured"
  ansible.builtin.debug:
      msg: "Warning!! NFTables is not supported in this role. Please use UFW, iptables, or manually manage nftables"
  when:
      - ubtu20cis_rule_3_5_2_7
      - ubtu20cis_firewall_package == "nftables"
  tags:
      - level1-server
      - level1-workstation
      - manual
      - audit
      - rule_3.5.2.7
      - nftables

- name: "3.5.2.8 | AUDIT | Ensure nftables default deny firewall policy"
  ansible.builtin.debug:
      msg: "Warning!! NFTables is not supported in this role. Please use UFW, iptables, or manually manage nftables"
  when:
      - ubtu20cis_rule_3_5_2_8
      - ubtu20cis_firewall_package == "nftables"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - audit
      - rule_3.5.2.8
      - nftables

- name: "3.5.2.9 | AUDIT | Ensure nftables service is enabled"
  ansible.builtin.debug:
      msg: "Warning!! NFTables is not supported in this role. Please use UFW, iptables, or manually manage nftables"
  # service:
  #     name: nftables
  #     state: started
  #     enabled: yes
  when:
      - ubtu20cis_rule_3_5_2_8
      - ubtu20cis_firewall_package == "nftables"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - audit
      - rule_3.5.2.9
      - nftables

- name: "3.5.2.10 | AUDIT | Ensure nftables rules are permanent"
  ansible.builtin.debug:
      msg: "Warning!! NFTables is not supported in this role. Please use UFW, iptables, or manually manage nftables"
  when:
      - ubtu20cis_rule_3_5_2_10
      - ubtu20cis_firewall_package == "nftables"
  tags:
      - level1-server
      - level1-workstation
      - automated
      - audit
      - rule_3.5.2.10
      - nftables
