---
- name: "3.1.1 | PATCH | Disable IPv6"
  block:
      - name: "3.1.1 | AUDIT | Disable IPv6 | Get current GRUB_CMDLINE_LINUX settings"
        ansible.builtin.shell: grep "GRUB_CMDLINE_LINUX=" /etc/default/grub | cut -f2 -d'"'
        changed_when: false
        failed_when: false
        check_mode: false
        register: ubtu20cis_3_1_1_grub_cmdline_linux_settings

      - name: "3.1.1 | PATCH | Disable IPv6 | Add ipv6.disable if does not exist"
        ansible.builtin.lineinfile:
            path: /etc/default/grub
            regexp: '^GRUB_CMDLINE_LINUX'
            line: 'GRUB_CMDLINE_LINUX="{{ ubtu20cis_3_1_1_grub_cmdline_linux_settings.stdout }} ipv6.disable=1"'
        when: "'ipv6.disable' not in ubtu20cis_3_1_1_grub_cmdline_linux_settings.stdout"
        notify: grub update

      - name: "3.1.1 | PATCH | Disable IPv6 | Set ipv6.disable to 1 if exists"
        ansible.builtin.replace:
            path: /etc/default/grub
            regexp: 'ipv6\.disable=.'
            replace: 'ipv6.disable=1'
        when: "'ipv6.disable' in ubtu20cis_3_1_1_grub_cmdline_linux_settings.stdout"
        notify: grub update

      - name: "3.1.1 | PATCH | Disable IPv6 | Remove net.ipv6.conf.all.disable_ipv6"
        ansible.builtin.lineinfile:
            path: /etc/sysctl.conf
            regexp: '^net.ipv6.conf.all.disable_ipv6.*'
            state: absent
  when:
      - ubtu20cis_rule_3_1_1
      - not ubtu20cis_ipv6_required
  tags:
      - level2-server
      - level2-workstation
      - manual
      - patch
      - rule_3.1.1
      - ipv6

- name: "3.1.2 | PATCH | Ensure wireless interfaces are disabled"
  block:
      - name: "3.1.2 | PATCH | Ensure wireless interfaces are disabled | Check for network-manager tool"
        ansible.builtin.shell: dpkg -l | grep network-manager
        changed_when: false
        failed_when: false
        check_mode: false
        register: ubtu20cis_3_1_2_network_manager_status

      - name: "3.1.2 | PATCH | Ensure wireless interfaces are disabled | Disable wireless if network-manager installed"
        ansible.builtin.shell: nmcli radio all off
        changed_when: ubtu20cis_3_1_2_nmcli_radio_off.rc == 0
        register: ubtu20cis_3_1_2_nmcli_radio_off
        when: ubtu20cis_3_1_2_network_manager_status.stdout | length > 0

      - name: "3.1.2 | AUDIT | Ensure wireless interfaces are disabled | Warn Count"
        ansible.builtin.import_tasks: warning_facts.yml
  vars:
      warn_control_id: '3.1.2'
  when:
      - ubtu20cis_rule_3_1_2
  tags:
      - level1-server
      - level2-workstation
      - automated
      - patch
      - rule_3.1.2
      - wireless
